require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.3

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
