require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
