openapi: 3.0.0
info:
  title: Productito
  version: 0.1.0
servers:
  - url: http://localhost:9292
paths:
  /:
    get:
      summary: Returns a hello world message
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /products:
    get:
      summary: Returns a list of products
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
    post:
      summary: Creates a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                  format: float
      responses:
        '200':
          description: Product creation scheduled
        '401':
          description: Unauthorized
  /products/{productId}:
    get:
      summary: Returns a specific product
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /AUTHORS:
    get:
      summary: Returns the AUTHORS file
      responses:
        '200':
          description: OK
  /foo:
    get:
      summary: Returns a 404 for non-existent route
      responses:
        '404':
          description: Not found
        '401':
          description: Unauthorized
